export const prompt = `You are an expert in DOM analysis and Puppeteer scraping.

You will receive input for the same Copart lot-details page:

An HTML body snapshot. Use it as the source of truth for selectors, containers, labels, and extraction strategy.

Your job is to generate a selector map and extraction plan that a Puppeteer scraper can use later to build this TypeScript object:

interface LotDetails {
  title: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  bodyStyle: string;
  runAndDrive: boolean;
  vin: string;
  lotNumber: string;
  laneItem: string;
  saleName: string;
  location: string;
  engineVerified: boolean;
  engineVerifiedNote: string;
  engineStatus: string;
  transmissionEngages: boolean;
  transmissionNote: string;
  titleCode: string;
  vehicleTitleType: string;
  odometer: number;
  odometerUnit: string;
  odometerStatus: string;
  primaryDamage: string;
  cylinders: string;
  color: string;
  hasKey: boolean;
  engineType: string;
  transmission: string;
  vehicleType: string;
  driveTrain: string;
  fuelType: string;
  saleDate: string;
  highlights: string[];
  notes: string;
  lastUpdated: string;
  currentBid: number;
  buyItNow: number | null;
  auctionName: string;
  auctionCountdown: string;
  images: string[];
  copartLink: string;
}

Rules:
- Treat the HTML body snapshot as the only source of truth for selectors.
- Do not guess selectors from the screenshot.
- Prefer stable selectors based on IDs, semantic classes, visible labels, nearby text anchors, aria attributes, data attributes, and repeated label/value structure.
- Avoid autogenerated classes, deep descendant chains, nth-child selectors, and framework noise such as .ng-star-inserted unless there is no better option.
- If several fields belong to the same repeated label/value block, return one shared container and the exact label text for each field.
- If a field is better derived from another field, mark it as derived instead of forcing a weak selector.
- If a field cannot be found reliably, return strategy as "not-found", selector as null, and explain why in notes.
- Return JSON only. Do not include markdown. Do not include commentary before or after the JSON.
- Every field must be present in the output.

Derivation rules:
- If title contains year, make, and model, mark year, make, and model as derived unless there is a clearly better dedicated source.
- For boolean fields such as runAndDrive, engineVerified, transmissionEngages, and hasKey, prefer describing the text source and boolean normalization rule in extract or notes.
- For odometer, return the text source for the full odometer string and describe how to parse the numeric value.
- For odometerUnit, derive from the odometer text when appropriate.
- For images, use a multi-element strategy and return a selector that can be used with $$eval.
- For copartLink, use page.url() instead of searching the DOM unless the page exposes a canonical URL element.

Output format:

{
  "pageType": "copart-lot",
  "containerSelectors": {
    "root": "",
    "header": "",
    "detailsSection": "",
    "saleSection": "",
    "biddingSection": "",
    "imageSection": ""
  },
  "fields": {
    "title": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "year": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "number",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "make": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "model": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "trim": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "bodyStyle": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "runAndDrive": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "boolean",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "vin": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "lotNumber": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "laneItem": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "saleName": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "location": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "engineVerified": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "boolean",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "engineVerifiedNote": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "engineStatus": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "transmissionEngages": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "boolean",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "transmissionNote": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "titleCode": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "vehicleTitleType": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "odometer": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "number",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "odometerUnit": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "odometerStatus": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "primaryDamage": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "cylinders": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "color": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "hasKey": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "boolean",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "engineType": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "transmission": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "vehicleType": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "driveTrain": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "fuelType": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "saleDate": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "highlights": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string[]",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "notes": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "lastUpdated": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "currentBid": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "number",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "buyItNow": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "number|null",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "auctionName": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "auctionCountdown": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "",
      "type": "string",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "images": {
      "selector": "",
      "strategy": "direct|label-based|derived|multi-element|not-found",
      "label": null,
      "container": "",
      "method": "$eval|$$eval|page.url",
      "extract": "Array.from(nodes).map(node => node.src || node.getAttribute('src')).filter(Boolean)",
      "type": "string[]",
      "confidence": "high|medium|low",
      "notes": ""
    },
    "copartLink": {
      "selector": "page.url()",
      "strategy": "derived",
      "label": null,
      "container": "",
      "method": "page.url",
      "extract": "page.url()",
      "type": "string",
      "confidence": "high",
      "notes": "Use the current page URL unless the HTML includes a better canonical link source."
    }
  }
}

Field-specific requirements:
- For label-based fields, set strategy to "label-based", set container to the shared repeated block, set label to the exact visible label text, and set selector to the best value selector or row selector that would be used with that label.
- For direct fields, provide the single best primary selector.
- For derived fields, describe the derivation clearly in notes.
- For multi-element fields, set method to "$$eval".
- Put fallback selector ideas in notes.
- Confidence must reflect how stable the selector appears in the HTML.

Assets:

HTML body snapshot:
[PASTE HTML SNAPSHOT HERE]`;

export default prompt;
