export const bodyType = ['Sedan', 'Coupe', 'Hatchback', 'SUV', 'Wagon', 'Convertible', 'Pickup', 'Van', 'Minivan', 'Crossover', 'Roadster', 'Truck', 'Other'];
export const sort = ['Relevance', 'Price (low to high)', 'Price (high to low)', 'Distance', 'Mileage', 'Age (newest)', 'Age (oldest)', 'Most recent'];
export const auctionName = ['Copart', 'IAAI', 'Manheim', 'Adesa', 'Insurance Auto Auctions', 'Salvage World', 'Other'];
export const cylinderType = ['2 Cylinder', '3 Cylinder', '4 Cylinder', '5 Cylinder', '6 Cylinder', '8 Cylinder', '10 Cylinder', '12 Cylinder', '16 Cylinder', 'Other'];
export const driveTrain = ['FWD', 'RWD', 'AWD', '4WD', 'Part-Time 4WD', 'Full-Time 4WD', 'Other'];
export const fuelType = ['Gasoline', 'Diesel', 'Electric', 'Hybrid', 'LPG', 'CNG', 'Hydrogen', 'Other'];
export const transmissionType = ['Automatic', 'Manual', 'CVT', 'Semi-Automatic', 'Dual-Clutch', 'Tiptronic', 'Other'];
export const engineType = ['0', '0.7L  2', '1.5L  3', '1.5L 3', '2.0L 4', '2.5L  6', '3.0L  6', '3.0L 6', '4.4L  8', '4.4L 8'];
export const vehicleType = [
	'ATVs',
	'Agriculture and Farm equipment',
	'Automobiles',
	'Boats',
	'Bus',
	'Construction equipment',
	'Dirt Bikes',
	'Heavy Duty Trucks',
	'Industrial Equipment',
	'Jet Skis',
	'Medium Duty Box Trucks',
	'Motorcycle',
	'Pickup Trucks',
	'RVs',
	'SUVs',
	'Snowmobile',
	'Trailers',
];
export const makes = [
	{ make: 'Acura', models: ['3.2TL', '3.5RL', 'MDX', 'RDX', 'TL', 'TLX', 'TSX'] },
	{ make: 'Alfa Romeo', models: [] },
	{ make: 'Audi', models: ['A3', 'A5', 'A6', 'E-TRON', 'Q3', 'Q5', 'S7'] },
	{ make: 'Bayliner', models: [] },
	{ make: 'Bentley', models: [] },
	{ make: 'Blue Bird', models: [] },
	{ make: 'Bmw', models: ['325', '328', '330XI', '528', '535', '540', 'M240XI', 'X3', 'X5', 'X6', 'X7'] },
	{ make: 'Bmw Motorrad', models: [] },
	{ make: 'Buick', models: ['LACROSSE'] },
	{ make: 'Cadillac', models: [] },
	{ make: 'Can-Am', models: [] },
	{ make: 'Chevrolet', models: ['CORVETTE', 'EQUINOX', 'EXPRESS G2500', 'IMPALA', 'IMPALA LIMITED', 'MALIBU', 'SILVERADO', 'SUBURBAN', 'TAHOE', 'TRAILBLAZER', 'TRAX', 'VOLT'] },
	{ make: 'Chrysler', models: ['200', '300', 'PACIFICA'] },
	{ make: 'Club Car', models: [] },
	{ make: 'Dodge', models: ['AVENGER', 'CHALLENGER', 'CHARGER', 'DURANGO', 'GRAND CARAVAN', 'RAM', 'RAM 2500'] },
	{ make: 'Ducati', models: [] },
	{ make: 'Fiat', models: [] },
	{ make: 'Ford', models: ['BRONCO SPORT', 'ECONOLINE', 'EDGE', 'ESCAPE', 'EXPLORER', 'F150', 'F250', 'FOCUS', 'FUSION', 'RANGER', 'TRANSIT', 'TRANSIT CONNECT'] },
	{ make: 'Freightliner', models: [] },
	{ make: 'Freigliner', models: [] },
	{ make: 'Genesis', models: [] },
	{ make: 'Gmc', models: ['ACADIA', 'NEW SIERRA', 'SAVANA', 'SIERRA', 'TERRAIN', 'YUKON'] },
	{ make: 'Great Dane', models: [] },
	{ make: 'Harley-Davidson', models: [] },
	{ make: 'Hino', models: [] },
	{ make: 'Honda', models: ['ACCORD', 'CIVIC', 'CR-V', 'HR-V', 'ODYSSEY', 'PILOT', 'RIDGELINE'] },
	{ make: 'Hummer', models: [] },
	{ make: 'Hyundai', models: ['ELANTRA', 'ELANTRA N', 'IONIQ 5', 'KONA', 'SANTA FE', 'SONATA', 'TUCSON', 'TUCSON HYBRID', 'VERACRUZ'] },
	{ make: 'Ic Corporation', models: ['3000', 'CE SERIES SCHOOL'] },
	{ make: 'Indian Motorcycle Co.', models: [] },
	{ make: 'Infiniti', models: ['G37 COUPE', 'JX35', 'Q50', 'QX60'] },
	{ make: 'Infinity', models: ['G37 COUPE', 'JX35', 'Q50', 'QX60'] },
	{ make: 'International', models: [] },
	{ make: 'Isuzu', models: [] },
	{ make: 'Jaguar', models: ['F-PACE'] },
	{ make: 'Jayco', models: [] },
	{ make: 'Jeep', models: ['CHEROKEE', 'COMPASS', 'GRAND CHEROKEE', 'LIBERTY', 'WRANGLER', 'WRANGLER UNLIMITED'] },
	{ make: 'John Deere', models: [] },
	{ make: 'Kawasaki', models: [] },
	{ make: 'Kenworth', models: [] },
	{ make: 'Keystone', models: [] },
	{ make: 'Kia', models: ['FORTE', 'K5', 'NIRO', 'SEDONA', 'SELTOS', 'SORENTO', 'SOUL', 'SPORTAGE', 'SPORTAGE HYBRID'] },
	{ make: 'Ktm', models: [] },
	{ make: 'Land Rover', models: ['DISCOVERY', 'LR2', 'LR4'] },
	{ make: 'Lexus', models: ['CT', 'ES 350', 'GX 460', 'GX 470', 'RX', 'RX 330', 'RX 350', 'RX 450H'] },
	{ make: 'Lincoln', models: ['MKT', 'MKZ'] },
	{ make: 'Lincoln Townhouse', models: ['MKT', 'MKZ'] },
	{ make: 'Lucid Motors', models: [] },
	{ make: 'Mack', models: [] },
	{ make: 'Maserati', models: [] },
	{ make: 'Mazda', models: ['3', 'CX-30', 'CX-5', 'CX-7', 'CX-9'] },
	{ make: 'Mercedes-Benz', models: ['C', 'E', 'EQE SEDAN', 'GL', 'GLB', 'GLC', 'GLE', 'GLS', 'ML'] },
	{ make: 'Mercury', models: [] },
	{ make: 'Mini', models: ['COOPER'] },
	{ make: 'Mitsubishi', models: ['OUTLANDER'] },
	{ make: 'Nissan', models: ['350Z', 'ALTIMA', 'ARMADA', 'FRONTIER', 'LEAF', 'MURANO', 'PATHFINDER', 'ROGUE', 'ROGUE SPORT', 'SENTRA', 'TITAN'] },
	{ make: 'Oldsmobile', models: [] },
	{ make: 'Other Motorcycle', models: [] },
	{ make: 'Peterbilt', models: [] },
	{ make: 'Peterbilt Tractor', models: [] },
	{ make: 'Polaris', models: [] },
	{ make: 'Polestar', models: [] },
	{ make: 'Pontiac', models: [] },
	{ make: 'Porsche', models: ['BOXSTER'] },
	{ make: 'Ram', models: ['1500', '1500 CLASSIC', '2500', 'PROMASTER 2500', 'PROMASTER CITY'] },
	{ make: 'Rivian', models: [] },
	{ make: 'Saab', models: [] },
	{ make: 'Saturn', models: [] },
	{ make: 'Scion', models: ['TC'] },
	{ make: 'Sea Doo', models: [] },
	{ make: 'Seadoo', models: [] },
	{ make: 'Smart', models: [] },
	{ make: 'Subaru', models: ['ASCENT', 'CROSSTREK', 'FORESTER', 'IMPREZA', 'LEGACY', 'OUTBACK'] },
	{ make: 'Suzuki', models: [] },
	{ make: 'Tesla', models: ['MODEL 3', 'MODEL X'] },
	{ make: 'Thomas', models: [] },
	{
		make: 'Toyota',
		models: [
			'4RUNNER',
			'C-HR',
			'CAMRY',
			'COROLLA',
			'HIGHLANDER',
			'HIGHLANDER HYBRID',
			'LAND CRUISER',
			'PRIUS',
			'PRIUS C',
			'PRIUS PRIME',
			'PRIUS V',
			'RAV4',
			'RAV4 HYBRID',
			'SEQUOIA',
			'SIENNA',
			'TACOMA',
			'TUNDRA',
			'VENZA',
			'YARIS',
		],
	},
	{ make: 'Triumph Motorcycle', models: [] },
	{ make: 'Unknown', models: [] },
	{ make: 'Utility', models: [] },
	{ make: 'Vanguard', models: [] },
	{ make: 'Volkswagen', models: ['CC', 'GOLF', 'GTI', 'JETTA', 'TIGUAN'] },
	{ make: 'Volvo', models: ['S60', 'XC60'] },
	{ make: 'Wabash', models: [] },
	{ make: 'Wildwood', models: [] },
	{ make: 'Wilson', models: [] },
	{ make: 'Workhorse Custom Chassis', models: [] },
	{ make: 'Yamaha', models: [] },
];
export const location = [
	'AL - BIRMINGHAM',
	'AL - MOBILE',
	'AL - MONTGOMERY',
	'AL - TANNER',
	'AR - FAYETTEVILLE',
	'AR - LITTLE ROCK',
	'AZ - PHOENIX',
	'CA - ADELANTO',
	'CA - MARTINEZ',
	'CA - MENTONE',
	'CA - RANCHO CUCAMONGA',
	'CA - SAN BERNARDINO',
	'CA - SAN DIEGO',
	'CA - SAN JOSE',
	'CA - SUN VALLEY',
	'CA - VAN NUYS',
	'CO - COLORADO SPRINGS',
	'CO - DENVER',
	'CO - DENVER CENTRAL',
	'CO - DENVER SOUTH',
	'CT - HARTFORD',
	'CT - HARTFORD SPRINGFIELD',
	'DC - WASHINGTON DC',
	'DE - SEAFORD',
	'FL - CLEWISTON',
	'FL - JACKSONVILLE NORTH',
	'FL - ORLANDO NORTH',
	'FL - ORLANDO SOUTH',
	'FL - TAMPA SOUTH',
	'GA - ATLANTA EAST',
	'GA - ATLANTA SOUTH',
	'GA - ATLANTA WEST',
	'HI - HONOLULU',
	'IL - CHICAGO NORTH',
	'IL - CHICAGO SOUTH',
	'IL - PEORIA',
	'IL - SOUTHERN ILLINOIS',
	'IN - CICERO',
	'IN - DYER',
	'IN - FORT WAYNE',
	'IN - INDIANAPOLIS',
	'KS - KANSAS CITY',
	'KS - WICHITA',
	'KY - EARLINGTON',
	'KY - LEXINGTON EAST',
	'KY - LEXINGTON WEST',
	'KY - LOUISVILLE',
	'LA - BATON ROUGE',
	'LA - NEW ORLEANS',
	'LA - SHREVEPORT',
	'MA - FREETOWN',
	'MA - NORTH BOSTON',
	'MD - BALTIMORE',
	'MD - BALTIMORE EAST',
	'ME - WINDHAM',
	'MI - DETROIT',
	'MI - FLINT',
	'MI - IONIA',
	'MI - WAYLAND',
	'MN - MINNEAPOLIS NORTH',
	'MN - ST. CLOUD',
	'MO - SPRINGFIELD',
	'MO - ST. LOUIS',
	'MS - JACKSON',
	'MT - HELENA',
	'NC - RALEIGH',
	'NE - LINCOLN',
	'NH - CANDIA',
	'NJ - GLASSBORO EAST',
	'NJ - SOMERVILLE',
	'NJ - TRENTON',
	'NM - ALBUQUERQUE',
	'NV - LAS VEGAS',
	'NV - LAS VEGAS WEST',
	'NY - LONG ISLAND',
	'NY - NEWBURGH',
	'OH - DAYTON',
	'OK - OKLAHOMA CITY',
	'OK - TULSA',
	'OR - PORTLAND NORTH',
	'PA - PHILADELPHIA',
	'QC - MONTREAL',
	'RI - EXETER',
	'SC - COLUMBIA',
	'SC - NORTH CHARLESTON',
	'SC - SPARTANBURG',
	'TN - KNOXVILLE',
	'TN - MEMPHIS',
	'TN - NASHVILLE',
	'TX - DALLAS',
	'TX - DALLAS SOUTH',
	'TX - FT. WORTH',
	'TX - HOUSTON',
	'TX - HOUSTON EAST',
	'TX - NORTH AUSTIN',
	'TX - SAN ANTONIO',
	'UT - SALT LAKE CITY',
	'VA - FREDERICKSBURG',
	'WA - GRAHAM',
	'WI - MILWAUKEE SOUTH',
];
export const titleType = ['Clean title', 'Non Repairable', 'Salvage'];
export const conditionType = ['Normal Wear', 'Low Damage', 'Medium - Heavy Damage'];
