export const bodyType = ['Sedan', 'Coupe', 'Hatchback', 'SUV', 'Wagon', 'Convertible', 'Pickup', 'Van', 'Minivan', 'Crossover', 'Roadster', 'Truck', 'Other'];

export const auctionName = ['Copart', 'IAAI', 'Manheim', 'Adesa', 'Insurance Auto Auctions', 'Salvage World', 'Other'];
export const cylinderType = ['2 Cylinder', '3 Cylinder', '4 Cylinder', '5 Cylinder', '6 Cylinder', '8 Cylinder', '10 Cylinder', '12 Cylinder', '16 Cylinder', 'Other'];
export const driveTrain = ['FWD', 'RWD', 'AWD', '4WD', 'Part-Time 4WD', 'Full-Time 4WD', 'Other'];
export const fuelType = ['Gasoline', 'Diesel', 'Electric', 'Hybrid', 'LPG', 'CNG', 'Hydrogen', 'Other'];
export const transmissionType = ['Automatic', 'Manual', 'CVT', 'Semi-Automatic', 'Dual-Clutch', 'Tiptronic', 'Other'];
export const engineType = ['4 Cylinder', '6 Cylinder', '8 Cylinder', '10 Cylinder', '12 Cylinder', 'Electric', 'Hybrid', 'Diesel', 'Gasoline', 'Rotary', 'Other'];
export const vehicleType = [
	'ATVs',
	'Agriculture and Farm equipment',
	'Automobiles',
	'Boats',
	'Bus',
	'Construction equipment',
	'Dirt Bikes',
	'Heavy Duty Trucks',
	'Industrial Equipment',
	'Jet Skis',
	'Medium Duty Box Trucks',
	'Motorcycle',
	'Pickup Trucks',
	'RVs',
	'SUVs',
	'Snowmobile',
	'Trailers',
];
export const makes = [
	'Acura',
	'Alfa Romeo',
	'Audi',
	'Bayliner',
	'Bentley',
	'Blue Bird',
	'Bmw',
	'Bmw Motorrad',
	'Buick',
	'Cadillac',
	'Can',
	'Can-Am',
	'Chev',
	'Chevrolet',
	'Chrysler',
	'Club Car',
	'Dodge',
	'Ducati',
	'Fiat',
	'Ford',
	'Freightliner',
	'Freigliner',
	'Genesis',
	'Gmc',
	'Great Dane',
	'Harley Davidson',
	'Harley-Davidson',
	'Hino',
	'Hond',
	'Honda',
	'Hummer',
	'Hyundai',
	'Ic Corporation',
	'Indian Motorcycle Co.',
	'Infiniti',
	'Infinity',
	'International',
	'Isuzu',
	'Jaguar',
	'Jayco',
	'Jeep',
	'John Deere',
	'Kawasaki',
	'Kenworth',
	'Keystone',
	'Kia',
	'Ktm',
	'Land Rover',
	'Lexus',
	'Lincoln',
	'Lincoln Townhouse',
	'Lucid Motors',
	'Mack',
	'Maserati',
	'Mazda',
	'Mercedes Benz',
	'Mercedes-Benz',
	'Mercury',
	'Mini',
	'Mitsubishi',
	'Niss',
	'Nissan',
	'Oeth',
	'Oldsmobile',
	'Oteh',
	'Other',
	'Other Motorcycle',
	'Others',
	'Peterbilt',
	'Peterbilt Tractor',
	'Pola',
	'Polaris',
	'Polestar',
	'Pontiac',
	'Porsche',
	'Ram',
	'Rivian',
	'Saab',
	'Saturn',
	'Scion',
	'Sea Doo',
	'Seadoo',
	'Smart',
	'Subaru',
	'Suzuki',
	'Tesla',
	'Thomas',
	'Toyota',
	'Toyt',
	'Triumph Motorcycle',
	'Unknown',
	'Utility',
	'Vanguard',
	'Volkswagen',
	'Volvo',
	'Wabash',
	'Wildwood',
	'Wilson',
	'Workhorse Custom Chassis',
	'Yamaha',
];
export const location = [
	'AL - BIRMINGHAM',
	'AL - MOBILE',
	'AL - MONTGOMERY',
	'AL - TANNER',
	'AR - FAYETTEVILLE',
	'AR - LITTLE ROCK',
	'AZ - PHOENIX',
	'CA - ADELANTO',
	'CA - MARTINEZ',
	'CA - MENTONE',
	'CA - RANCHO CUCAMONGA',
	'CA - SAN BERNARDINO',
	'CA - SAN DIEGO',
	'CA - SAN JOSE',
	'CA - SUN VALLEY',
	'CA - VAN NUYS',
	'CO - COLORADO SPRINGS',
	'CO - DENVER',
	'CO - DENVER CENTRAL',
	'CO - DENVER SOUTH',
	'CT - HARTFORD',
	'CT - HARTFORD SPRINGFIELD',
	'DC - WASHINGTON DC',
	'DE - SEAFORD',
	'FL - CLEWISTON',
	'FL - JACKSONVILLE NORTH',
	'FL - ORLANDO NORTH',
	'FL - ORLANDO SOUTH',
	'FL - TAMPA SOUTH',
	'GA - ATLANTA EAST',
	'GA - ATLANTA SOUTH',
	'GA - ATLANTA WEST',
	'HI - HONOLULU',
	'IL - CHICAGO NORTH',
	'IL - CHICAGO SOUTH',
	'IL - PEORIA',
	'IL - SOUTHERN ILLINOIS',
	'IN - CICERO',
	'IN - DYER',
	'IN - FORT WAYNE',
	'IN - INDIANAPOLIS',
	'KS - KANSAS CITY',
	'KS - WICHITA',
	'KY - EARLINGTON',
	'KY - LEXINGTON EAST',
	'KY - LEXINGTON WEST',
	'KY - LOUISVILLE',
	'LA - BATON ROUGE',
	'LA - NEW ORLEANS',
	'LA - SHREVEPORT',
	'MA - FREETOWN',
	'MA - NORTH BOSTON',
	'MD - BALTIMORE',
	'MD - BALTIMORE EAST',
	'ME - WINDHAM',
	'MI - DETROIT',
	'MI - FLINT',
	'MI - IONIA',
	'MI - WAYLAND',
	'MN - MINNEAPOLIS NORTH',
	'MN - ST. CLOUD',
	'MO - SPRINGFIELD',
	'MO - ST. LOUIS',
	'MS - JACKSON',
	'MT - HELENA',
	'NC - RALEIGH',
	'NE - LINCOLN',
	'NH - CANDIA',
	'NJ - GLASSBORO EAST',
	'NJ - SOMERVILLE',
	'NJ - TRENTON',
	'NM - ALBUQUERQUE',
	'NV - LAS VEGAS',
	'NV - LAS VEGAS WEST',
	'NY - LONG ISLAND',
	'NY - NEWBURGH',
	'OH - DAYTON',
	'OK - OKLAHOMA CITY',
	'OK - TULSA',
	'OR - PORTLAND NORTH',
	'PA - PHILADELPHIA',
	'QC - MONTREAL',
	'RI - EXETER',
	'SC - COLUMBIA',
	'SC - NORTH CHARLESTON',
	'SC - SPARTANBURG',
	'TN - KNOXVILLE',
	'TN - MEMPHIS',
	'TN - NASHVILLE',
	'TX - DALLAS',
	'TX - DALLAS SOUTH',
	'TX - FT. WORTH',
	'TX - HOUSTON',
	'TX - HOUSTON EAST',
	'TX - NORTH AUSTIN',
	'TX - SAN ANTONIO',
	'UT - SALT LAKE CITY',
	'VA - FREDERICKSBURG',
	'WA - GRAHAM',
	'WI - MILWAUKEE SOUTH',
];
export const titleType = ['Clean title', 'Non Repaireble', 'Salvage'];
export const conditionType = ['Norrmal Wear', 'Low Damage', 'Medium - Heavy Damage'];
